CI/CD

diff --git a/.github/workflows/docker-image.yml b/.github/workflows/docker-image.yml
--- a/.github/workflows/docker-image.yml
+++ b/.github/workflows/docker-image.yml
@@ -14,27 +14,21 @@ jobs:
     container:
       image: jhonatancaldeira/python-base:3.10
 
-    services:
-      rabbitmq:
-        image: rabbitmq:3-management
-        ports:
-          - 5672:5672
-          - 15672:15672
-        options: >-
-          --health-cmd="rabbitmq-diagnostics -q ping"
-          --health-interval=10s
-          --health-timeout=5s
-          --health-retries=5
+    # services:
+    #   rabbitmq:
+    #     image: rabbitmq:3-management
+    #     ports:
+    #       - 5672:5672
+    #       - 15672:15672
+    #     options: >-
+    #       --health-cmd="rabbitmq-diagnostics -q ping"
+    #       --health-interval=10s
+    #       --health-timeout=5s
+    #       --health-retries=5
 
     steps:
       - name: Checkout repository
         uses: actions/checkout@v4
-
-      # Étape pour installer Docker Compose
-      - name: Set up Docker Compose
-        run: |
-         sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
-         sudo chmod +x /usr/local/bin/docker-compose
           
       - name: Pass secrets as environment variables
         run: |
@@ -63,11 +57,13 @@ jobs:
           echo "OBJ_DETECTION_MODEL_NAME=${{ secrets.OBJ_DETECTION_MODEL_NAME }}" >> .env
           echo "CLASSIFICATION_MODEL_NAME=${{ secrets.CLASSIFICATION_MODEL_NAME }}" >> .env
           echo "SEGMENTATION_MODEL_NAME=${{ secrets.SEGMENTATION_MODEL_NAME }}" >> .env
-          cat .env
 
-      - name: Build and Test Docker Compose
+      - name: Run docker-compose
+        uses: hoverkraft-tech/compose-action@v2.0.1
+        with:
+          compose-file: "./docker-compose.yml"
+
+      - name: Test Docker Compose
         run: |
-          docker-compose -f docker-compose.yml up --build --detach
           docker ps -a
-          docker-compose exec models_api curl -I http://localhost:5005 || exit 1
-          docker-compose down
+          docker-compose exec pytest tests/api_test.py || exit 1 # Run 
